// Generated block-id cache — every `B.<name>` used in the codebase becomes a
// stored UInt16 resolved ONCE after block registration. Real members shadow
// the @dynamicMemberLookup subscript, so `B.stone` is now a direct load
// instead of a per-access string hash + dictionary find (which dominated
// chunk lighting, collision and the mesher).
// Regenerate: grep -ohE '\\bB\\.[a-z_0-9]+' Sources/**/*.swift | sort -u

@dynamicMemberLookup
public struct ResolvedBlockIDs {
    public var acacia_leaves: UInt16 = 0
    public var acacia_log: UInt16 = 0
    public var acacia_sapling: UInt16 = 0
    public var activator_rail: UInt16 = 0
    public var air: UInt16 = 0
    public var allium: UInt16 = 0
    public var amethyst_block: UInt16 = 0
    public var amethyst_cluster: UInt16 = 0
    public var ancient_debris: UInt16 = 0
    public var andesite: UInt16 = 0
    public var anvil: UInt16 = 0
    public var azalea: UInt16 = 0
    public var azalea_leaves: UInt16 = 0
    public var azure_bluet: UInt16 = 0
    public var bamboo: UInt16 = 0
    public var bamboo_sapling: UInt16 = 0
    public var barrel: UInt16 = 0
    public var basalt: UInt16 = 0
    public var beacon: UInt16 = 0
    public var bedrock: UInt16 = 0
    public var bee_nest: UInt16 = 0
    public var beehive: UInt16 = 0
    public var beetroots: UInt16 = 0
    public var bell: UInt16 = 0
    public var big_dripleaf: UInt16 = 0
    public var big_dripleaf_stem: UInt16 = 0
    public var birch_leaves: UInt16 = 0
    public var birch_log: UInt16 = 0
    public var birch_planks: UInt16 = 0
    public var birch_sapling: UInt16 = 0
    public var blackstone: UInt16 = 0
    public var blast_furnace: UInt16 = 0
    public var blast_furnace_lit: UInt16 = 0
    public var blue_ice: UInt16 = 0
    public var blue_orchid: UInt16 = 0
    public var blue_terracotta: UInt16 = 0
    public var bone_block: UInt16 = 0
    public var bookshelf: UInt16 = 0
    public var brewing_stand: UInt16 = 0
    public var bricks: UInt16 = 0
    public var brown_mushroom: UInt16 = 0
    public var brown_mushroom_block: UInt16 = 0
    public var brown_terracotta: UInt16 = 0
    public var budding_amethyst: UInt16 = 0
    public var cactus: UInt16 = 0
    public var cake: UInt16 = 0
    public var calcite: UInt16 = 0
    public var calibrated_sculk_sensor: UInt16 = 0
    public var campfire: UInt16 = 0
    public var candle: UInt16 = 0
    public var carrots: UInt16 = 0
    public var cartography_table: UInt16 = 0
    public var carved_pumpkin: UInt16 = 0
    public var cauldron: UInt16 = 0
    public var cave_air: UInt16 = 0
    public var cave_vines: UInt16 = 0
    public var cave_vines_plant: UInt16 = 0
    public var cherry_leaves: UInt16 = 0
    public var cherry_log: UInt16 = 0
    public var cherry_sapling: UInt16 = 0
    public var chest: UInt16 = 0
    public var chipped_anvil: UInt16 = 0
    public var chiseled_bookshelf: UInt16 = 0
    public var chiseled_sandstone: UInt16 = 0
    public var chorus_flower: UInt16 = 0
    public var chorus_plant: UInt16 = 0
    public var clay: UInt16 = 0
    public var coal_ore: UInt16 = 0
    public var coarse_dirt: UInt16 = 0
    public var cobbled_deepslate: UInt16 = 0
    public var cobblestone: UInt16 = 0
    public var cobblestone_stairs: UInt16 = 0
    public var cobweb: UInt16 = 0
    public var cocoa: UInt16 = 0
    public var comparator: UInt16 = 0
    public var comparator_on: UInt16 = 0
    public var composter: UInt16 = 0
    public var conduit: UInt16 = 0
    public var copper_ore: UInt16 = 0
    public var cornflower: UInt16 = 0
    public var cracked_deepslate_bricks: UInt16 = 0
    public var cracked_polished_blackstone_bricks: UInt16 = 0
    public var cracked_stone_bricks: UInt16 = 0
    public var crafting_table: UInt16 = 0
    public var crimson_fungus: UInt16 = 0
    public var crimson_nylium: UInt16 = 0
    public var crimson_roots: UInt16 = 0
    public var crimson_stem: UInt16 = 0
    public var crying_obsidian: UInt16 = 0
    public var cut_sandstone: UInt16 = 0
    public var damaged_anvil: UInt16 = 0
    public var dandelion: UInt16 = 0
    public var dark_oak_fence: UInt16 = 0
    public var dark_oak_leaves: UInt16 = 0
    public var dark_oak_log: UInt16 = 0
    public var dark_oak_planks: UInt16 = 0
    public var dark_oak_sapling: UInt16 = 0
    public var dark_oak_slab: UInt16 = 0
    public var dark_oak_stairs: UInt16 = 0
    public var dark_prismarine: UInt16 = 0
    public var daylight_detector: UInt16 = 0
    public var daylight_detector_inverted: UInt16 = 0
    public var decorated_pot: UInt16 = 0
    public var deepslate: UInt16 = 0
    public var deepslate_bricks: UInt16 = 0
    public var deepslate_coal_ore: UInt16 = 0
    public var deepslate_copper_ore: UInt16 = 0
    public var deepslate_diamond_ore: UInt16 = 0
    public var deepslate_emerald_ore: UInt16 = 0
    public var deepslate_gold_ore: UInt16 = 0
    public var deepslate_iron_ore: UInt16 = 0
    public var deepslate_lapis_ore: UInt16 = 0
    public var deepslate_redstone_ore: UInt16 = 0
    public var deepslate_tiles: UInt16 = 0
    public var detector_rail: UInt16 = 0
    public var diamond_block: UInt16 = 0
    public var diamond_ore: UInt16 = 0
    public var diorite: UInt16 = 0
    public var dirt: UInt16 = 0
    public var dirt_path: UInt16 = 0
    public var dispenser: UInt16 = 0
    public var dragon_egg: UInt16 = 0
    public var dragon_head: UInt16 = 0
    public var dripstone_block: UInt16 = 0
    public var dropper: UInt16 = 0
    public var emerald_block: UInt16 = 0
    public var emerald_ore: UInt16 = 0
    public var enchanting_table: UInt16 = 0
    public var end_gateway: UInt16 = 0
    public var end_portal: UInt16 = 0
    public var end_portal_frame: UInt16 = 0
    public var end_rod: UInt16 = 0
    public var end_stone: UInt16 = 0
    public var end_stone_bricks: UInt16 = 0
    public var ender_chest: UInt16 = 0
    public var farmland: UInt16 = 0
    public var fire: UInt16 = 0
    public var fletching_table: UInt16 = 0
    public var flower_pot: UInt16 = 0
    public var flowering_azalea: UInt16 = 0
    public var flowering_azalea_leaves: UInt16 = 0
    public var frogspawn: UInt16 = 0
    public var frosted_ice: UInt16 = 0
    public var furnace: UInt16 = 0
    public var furnace_lit: UInt16 = 0
    public var gilded_blackstone: UInt16 = 0
    public var glass: UInt16 = 0
    public var glass_pane: UInt16 = 0
    public var glowstone: UInt16 = 0
    public var gold_block: UInt16 = 0
    public var gold_ore: UInt16 = 0
    public var granite: UInt16 = 0
    public var grass_block: UInt16 = 0
    public var gravel: UInt16 = 0
    public var gray_carpet: UInt16 = 0
    public var gray_wool: UInt16 = 0
    public var grindstone: UInt16 = 0
    public var hay_block: UInt16 = 0
    public var heavy_weighted_pressure_plate: UInt16 = 0
    public var honey_block: UInt16 = 0
    public var hopper: UInt16 = 0
    public var ice: UInt16 = 0
    public var infested_stone_bricks: UInt16 = 0
    public var iron_bars: UInt16 = 0
    public var iron_block: UInt16 = 0
    public var iron_door: UInt16 = 0
    public var iron_ore: UInt16 = 0
    public var iron_trapdoor: UInt16 = 0
    public var jack_o_lantern: UInt16 = 0
    public var jukebox: UInt16 = 0
    public var jungle_leaves: UInt16 = 0
    public var jungle_log: UInt16 = 0
    public var jungle_sapling: UInt16 = 0
    public var kelp: UInt16 = 0
    public var kelp_plant: UInt16 = 0
    public var ladder: UInt16 = 0
    public var lantern: UInt16 = 0
    public var lapis_ore: UInt16 = 0
    public var large_amethyst_bud: UInt16 = 0
    public var lava: UInt16 = 0
    public var lectern: UInt16 = 0
    public var lever: UInt16 = 0
    public var light_gray_terracotta: UInt16 = 0
    public var light_weighted_pressure_plate: UInt16 = 0
    public var lightning_rod: UInt16 = 0
    public var lilac: UInt16 = 0
    public var lily_of_the_valley: UInt16 = 0
    public var lily_pad: UInt16 = 0
    public var lodestone: UInt16 = 0
    public var loom: UInt16 = 0
    public var magma_block: UInt16 = 0
    public var mangrove_leaves: UInt16 = 0
    public var mangrove_log: UInt16 = 0
    public var mangrove_propagule: UInt16 = 0
    public var mangrove_roots: UInt16 = 0
    public var medium_amethyst_bud: UInt16 = 0
    public var melon: UInt16 = 0
    public var melon_stem: UInt16 = 0
    public var moss_block: UInt16 = 0
    public var moss_carpet: UInt16 = 0
    public var mossy_cobblestone: UInt16 = 0
    public var mossy_stone_bricks: UInt16 = 0
    public var mud: UInt16 = 0
    public var mud_bricks: UInt16 = 0
    public var muddy_mangrove_roots: UInt16 = 0
    public var mushroom_stem: UInt16 = 0
    public var mycelium: UInt16 = 0
    public var nether_brick_fence: UInt16 = 0
    public var nether_brick_stairs: UInt16 = 0
    public var nether_bricks: UInt16 = 0
    public var nether_gold_ore: UInt16 = 0
    public var nether_portal: UInt16 = 0
    public var nether_quartz_ore: UInt16 = 0
    public var nether_sprouts: UInt16 = 0
    public var nether_wart: UInt16 = 0
    public var nether_wart_block: UInt16 = 0
    public var netherite_block: UInt16 = 0
    public var netherrack: UInt16 = 0
    public var note_block: UInt16 = 0
    public var oak_door: UInt16 = 0
    public var oak_fence: UInt16 = 0
    public var oak_leaves: UInt16 = 0
    public var oak_log: UInt16 = 0
    public var oak_planks: UInt16 = 0
    public var oak_sapling: UInt16 = 0
    public var oak_trapdoor: UInt16 = 0
    public var observer: UInt16 = 0
    public var obsidian: UInt16 = 0
    public var orange_terracotta: UInt16 = 0
    public var orange_tulip: UInt16 = 0
    public var oxeye_daisy: UInt16 = 0
    public var packed_ice: UInt16 = 0
    public var packed_mud: UInt16 = 0
    public var peony: UInt16 = 0
    public var pink_tulip: UInt16 = 0
    public var piston: UInt16 = 0
    public var piston_head: UInt16 = 0
    public var pitcher_crop: UInt16 = 0
    public var pitcher_plant: UInt16 = 0
    public var podzol: UInt16 = 0
    public var pointed_dripstone: UInt16 = 0
    public var polished_blackstone_bricks: UInt16 = 0
    public var polished_blackstone_button: UInt16 = 0
    public var polished_blackstone_pressure_plate: UInt16 = 0
    public var poppy: UInt16 = 0
    public var potatoes: UInt16 = 0
    public var powder_snow: UInt16 = 0
    public var powered_rail: UInt16 = 0
    public var prismarine: UInt16 = 0
    public var prismarine_bricks: UInt16 = 0
    public var pumpkin: UInt16 = 0
    public var pumpkin_stem: UInt16 = 0
    public var purple_stained_glass: UInt16 = 0
    public var purpur_block: UInt16 = 0
    public var purpur_pillar: UInt16 = 0
    public var purpur_slab: UInt16 = 0
    public var purpur_stairs: UInt16 = 0
    public var rail: UInt16 = 0
    public var red_bed: UInt16 = 0
    public var red_carpet: UInt16 = 0
    public var red_mushroom: UInt16 = 0
    public var red_mushroom_block: UInt16 = 0
    public var red_sand: UInt16 = 0
    public var red_sandstone: UInt16 = 0
    public var red_terracotta: UInt16 = 0
    public var red_tulip: UInt16 = 0
    public var redstone_block: UInt16 = 0
    public var redstone_lamp: UInt16 = 0
    public var redstone_lamp_on: UInt16 = 0
    public var redstone_ore: UInt16 = 0
    public var redstone_torch: UInt16 = 0
    public var redstone_torch_off: UInt16 = 0
    public var redstone_wire: UInt16 = 0
    public var reinforced_deepslate: UInt16 = 0
    public var repeater: UInt16 = 0
    public var repeater_on: UInt16 = 0
    public var respawn_anchor: UInt16 = 0
    public var rooted_dirt: UInt16 = 0
    public var rose_bush: UInt16 = 0
    public var sand: UInt16 = 0
    public var sandstone: UInt16 = 0
    public var sandstone_slab: UInt16 = 0
    public var sandstone_stairs: UInt16 = 0
    public var sandstone_wall: UInt16 = 0
    public var sculk: UInt16 = 0
    public var sculk_catalyst: UInt16 = 0
    public var sculk_sensor: UInt16 = 0
    public var sculk_shrieker: UInt16 = 0
    public var sculk_vein: UInt16 = 0
    public var sea_lantern: UInt16 = 0
    public var sea_pickle: UInt16 = 0
    public var short_grass: UInt16 = 0
    public var shroomlight: UInt16 = 0
    public var shulker_box: UInt16 = 0
    public var skeleton_skull: UInt16 = 0
    public var slime_block: UInt16 = 0
    public var small_amethyst_bud: UInt16 = 0
    public var small_dripleaf: UInt16 = 0
    public var smithing_table: UInt16 = 0
    public var smoker: UInt16 = 0
    public var smoker_lit: UInt16 = 0
    public var smooth_basalt: UInt16 = 0
    public var smooth_sandstone: UInt16 = 0
    public var sniffer_egg: UInt16 = 0
    public var snow: UInt16 = 0
    public var snow_block: UInt16 = 0
    public var soul_campfire: UInt16 = 0
    public var soul_fire: UInt16 = 0
    public var soul_lantern: UInt16 = 0
    public var soul_sand: UInt16 = 0
    public var soul_soil: UInt16 = 0
    public var spawner: UInt16 = 0
    public var spore_blossom: UInt16 = 0
    public var spruce_leaves: UInt16 = 0
    public var spruce_log: UInt16 = 0
    public var spruce_planks: UInt16 = 0
    public var spruce_sapling: UInt16 = 0
    public var sticky_piston: UInt16 = 0
    public var stone: UInt16 = 0
    public var stone_brick_slab: UInt16 = 0
    public var stone_brick_stairs: UInt16 = 0
    public var stone_bricks: UInt16 = 0
    public var stone_button: UInt16 = 0
    public var stone_pressure_plate: UInt16 = 0
    public var stonecutter: UInt16 = 0
    public var sugar_cane: UInt16 = 0
    public var suspicious_gravel: UInt16 = 0
    public var suspicious_sand: UInt16 = 0
    public var sweet_berry_bush: UInt16 = 0
    public var tall_grass: UInt16 = 0
    public var tall_seagrass: UInt16 = 0
    public var target: UInt16 = 0
    public var terracotta: UInt16 = 0
    public var tnt: UInt16 = 0
    public var torch: UInt16 = 0
    public var torchflower: UInt16 = 0
    public var torchflower_crop: UInt16 = 0
    public var trapped_chest: UInt16 = 0
    public var tripwire: UInt16 = 0
    public var tripwire_hook: UInt16 = 0
    public var tuff: UInt16 = 0
    public var turtle_egg: UInt16 = 0
    public var twisting_vines: UInt16 = 0
    public var vine: UInt16 = 0
    public var void_air: UInt16 = 0
    public var warped_fungus: UInt16 = 0
    public var warped_nylium: UInt16 = 0
    public var warped_roots: UInt16 = 0
    public var warped_stem: UInt16 = 0
    public var warped_wart_block: UInt16 = 0
    public var water: UInt16 = 0
    public var weeping_vines: UInt16 = 0
    public var wet_sponge: UInt16 = 0
    public var wheat: UInt16 = 0
    public var white_carpet: UInt16 = 0
    public var white_terracotta: UInt16 = 0
    public var white_tulip: UInt16 = 0
    public var white_wool: UInt16 = 0
    public var wither_skeleton_skull: UInt16 = 0
    public var yellow_terracotta: UInt16 = 0

    @inline(__always)
    public subscript(dynamicMember name: String) -> UInt16 { bid(name) }
    public subscript(_ name: String) -> UInt16 { bid(name) }
}

public func populateBlockIDs() {
    var b = ResolvedBlockIDs()
    b.acacia_leaves = bid("acacia_leaves")
    b.acacia_log = bid("acacia_log")
    b.acacia_sapling = bid("acacia_sapling")
    b.activator_rail = bid("activator_rail")
    b.air = bid("air")
    b.allium = bid("allium")
    b.amethyst_block = bid("amethyst_block")
    b.amethyst_cluster = bid("amethyst_cluster")
    b.ancient_debris = bid("ancient_debris")
    b.andesite = bid("andesite")
    b.anvil = bid("anvil")
    b.azalea = bid("azalea")
    b.azalea_leaves = bid("azalea_leaves")
    b.azure_bluet = bid("azure_bluet")
    b.bamboo = bid("bamboo")
    b.bamboo_sapling = bid("bamboo_sapling")
    b.barrel = bid("barrel")
    b.basalt = bid("basalt")
    b.beacon = bid("beacon")
    b.bedrock = bid("bedrock")
    b.bee_nest = bid("bee_nest")
    b.beehive = bid("beehive")
    b.beetroots = bid("beetroots")
    b.bell = bid("bell")
    b.big_dripleaf = bid("big_dripleaf")
    b.big_dripleaf_stem = bid("big_dripleaf_stem")
    b.birch_leaves = bid("birch_leaves")
    b.birch_log = bid("birch_log")
    b.birch_planks = bid("birch_planks")
    b.birch_sapling = bid("birch_sapling")
    b.blackstone = bid("blackstone")
    b.blast_furnace = bid("blast_furnace")
    b.blast_furnace_lit = bid("blast_furnace_lit")
    b.blue_ice = bid("blue_ice")
    b.blue_orchid = bid("blue_orchid")
    b.blue_terracotta = bid("blue_terracotta")
    b.bone_block = bid("bone_block")
    b.bookshelf = bid("bookshelf")
    b.brewing_stand = bid("brewing_stand")
    b.bricks = bid("bricks")
    b.brown_mushroom = bid("brown_mushroom")
    b.brown_mushroom_block = bid("brown_mushroom_block")
    b.brown_terracotta = bid("brown_terracotta")
    b.budding_amethyst = bid("budding_amethyst")
    b.cactus = bid("cactus")
    b.cake = bid("cake")
    b.calcite = bid("calcite")
    b.calibrated_sculk_sensor = bid("calibrated_sculk_sensor")
    b.campfire = bid("campfire")
    b.candle = bid("candle")
    b.carrots = bid("carrots")
    b.cartography_table = bid("cartography_table")
    b.carved_pumpkin = bid("carved_pumpkin")
    b.cauldron = bid("cauldron")
    b.cave_air = bid("cave_air")
    b.cave_vines = bid("cave_vines")
    b.cave_vines_plant = bid("cave_vines_plant")
    b.cherry_leaves = bid("cherry_leaves")
    b.cherry_log = bid("cherry_log")
    b.cherry_sapling = bid("cherry_sapling")
    b.chest = bid("chest")
    b.chipped_anvil = bid("chipped_anvil")
    b.chiseled_bookshelf = bid("chiseled_bookshelf")
    b.chiseled_sandstone = bid("chiseled_sandstone")
    b.chorus_flower = bid("chorus_flower")
    b.chorus_plant = bid("chorus_plant")
    b.clay = bid("clay")
    b.coal_ore = bid("coal_ore")
    b.coarse_dirt = bid("coarse_dirt")
    b.cobbled_deepslate = bid("cobbled_deepslate")
    b.cobblestone = bid("cobblestone")
    b.cobblestone_stairs = bid("cobblestone_stairs")
    b.cobweb = bid("cobweb")
    b.cocoa = bid("cocoa")
    b.comparator = bid("comparator")
    b.comparator_on = bid("comparator_on")
    b.composter = bid("composter")
    b.conduit = bid("conduit")
    b.copper_ore = bid("copper_ore")
    b.cornflower = bid("cornflower")
    b.cracked_deepslate_bricks = bid("cracked_deepslate_bricks")
    b.cracked_polished_blackstone_bricks = bid("cracked_polished_blackstone_bricks")
    b.cracked_stone_bricks = bid("cracked_stone_bricks")
    b.crafting_table = bid("crafting_table")
    b.crimson_fungus = bid("crimson_fungus")
    b.crimson_nylium = bid("crimson_nylium")
    b.crimson_roots = bid("crimson_roots")
    b.crimson_stem = bid("crimson_stem")
    b.crying_obsidian = bid("crying_obsidian")
    b.cut_sandstone = bid("cut_sandstone")
    b.damaged_anvil = bid("damaged_anvil")
    b.dandelion = bid("dandelion")
    b.dark_oak_fence = bid("dark_oak_fence")
    b.dark_oak_leaves = bid("dark_oak_leaves")
    b.dark_oak_log = bid("dark_oak_log")
    b.dark_oak_planks = bid("dark_oak_planks")
    b.dark_oak_sapling = bid("dark_oak_sapling")
    b.dark_oak_slab = bid("dark_oak_slab")
    b.dark_oak_stairs = bid("dark_oak_stairs")
    b.dark_prismarine = bid("dark_prismarine")
    b.daylight_detector = bid("daylight_detector")
    b.daylight_detector_inverted = bid("daylight_detector_inverted")
    b.decorated_pot = bid("decorated_pot")
    b.deepslate = bid("deepslate")
    b.deepslate_bricks = bid("deepslate_bricks")
    b.deepslate_coal_ore = bid("deepslate_coal_ore")
    b.deepslate_copper_ore = bid("deepslate_copper_ore")
    b.deepslate_diamond_ore = bid("deepslate_diamond_ore")
    b.deepslate_emerald_ore = bid("deepslate_emerald_ore")
    b.deepslate_gold_ore = bid("deepslate_gold_ore")
    b.deepslate_iron_ore = bid("deepslate_iron_ore")
    b.deepslate_lapis_ore = bid("deepslate_lapis_ore")
    b.deepslate_redstone_ore = bid("deepslate_redstone_ore")
    b.deepslate_tiles = bid("deepslate_tiles")
    b.detector_rail = bid("detector_rail")
    b.diamond_block = bid("diamond_block")
    b.diamond_ore = bid("diamond_ore")
    b.diorite = bid("diorite")
    b.dirt = bid("dirt")
    b.dirt_path = bid("dirt_path")
    b.dispenser = bid("dispenser")
    b.dragon_egg = bid("dragon_egg")
    b.dragon_head = bid("dragon_head")
    b.dripstone_block = bid("dripstone_block")
    b.dropper = bid("dropper")
    b.emerald_block = bid("emerald_block")
    b.emerald_ore = bid("emerald_ore")
    b.enchanting_table = bid("enchanting_table")
    b.end_gateway = bid("end_gateway")
    b.end_portal = bid("end_portal")
    b.end_portal_frame = bid("end_portal_frame")
    b.end_rod = bid("end_rod")
    b.end_stone = bid("end_stone")
    b.end_stone_bricks = bid("end_stone_bricks")
    b.ender_chest = bid("ender_chest")
    b.farmland = bid("farmland")
    b.fire = bid("fire")
    b.fletching_table = bid("fletching_table")
    b.flower_pot = bid("flower_pot")
    b.flowering_azalea = bid("flowering_azalea")
    b.flowering_azalea_leaves = bid("flowering_azalea_leaves")
    b.frogspawn = bid("frogspawn")
    b.frosted_ice = bid("frosted_ice")
    b.furnace = bid("furnace")
    b.furnace_lit = bid("furnace_lit")
    b.gilded_blackstone = bid("gilded_blackstone")
    b.glass = bid("glass")
    b.glass_pane = bid("glass_pane")
    b.glowstone = bid("glowstone")
    b.gold_block = bid("gold_block")
    b.gold_ore = bid("gold_ore")
    b.granite = bid("granite")
    b.grass_block = bid("grass_block")
    b.gravel = bid("gravel")
    b.gray_carpet = bid("gray_carpet")
    b.gray_wool = bid("gray_wool")
    b.grindstone = bid("grindstone")
    b.hay_block = bid("hay_block")
    b.heavy_weighted_pressure_plate = bid("heavy_weighted_pressure_plate")
    b.honey_block = bid("honey_block")
    b.hopper = bid("hopper")
    b.ice = bid("ice")
    b.infested_stone_bricks = bid("infested_stone_bricks")
    b.iron_bars = bid("iron_bars")
    b.iron_block = bid("iron_block")
    b.iron_door = bid("iron_door")
    b.iron_ore = bid("iron_ore")
    b.iron_trapdoor = bid("iron_trapdoor")
    b.jack_o_lantern = bid("jack_o_lantern")
    b.jukebox = bid("jukebox")
    b.jungle_leaves = bid("jungle_leaves")
    b.jungle_log = bid("jungle_log")
    b.jungle_sapling = bid("jungle_sapling")
    b.kelp = bid("kelp")
    b.kelp_plant = bid("kelp_plant")
    b.ladder = bid("ladder")
    b.lantern = bid("lantern")
    b.lapis_ore = bid("lapis_ore")
    b.large_amethyst_bud = bid("large_amethyst_bud")
    b.lava = bid("lava")
    b.lectern = bid("lectern")
    b.lever = bid("lever")
    b.light_gray_terracotta = bid("light_gray_terracotta")
    b.light_weighted_pressure_plate = bid("light_weighted_pressure_plate")
    b.lightning_rod = bid("lightning_rod")
    b.lilac = bid("lilac")
    b.lily_of_the_valley = bid("lily_of_the_valley")
    b.lily_pad = bid("lily_pad")
    b.lodestone = bid("lodestone")
    b.loom = bid("loom")
    b.magma_block = bid("magma_block")
    b.mangrove_leaves = bid("mangrove_leaves")
    b.mangrove_log = bid("mangrove_log")
    b.mangrove_propagule = bid("mangrove_propagule")
    b.mangrove_roots = bid("mangrove_roots")
    b.medium_amethyst_bud = bid("medium_amethyst_bud")
    b.melon = bid("melon")
    b.melon_stem = bid("melon_stem")
    b.moss_block = bid("moss_block")
    b.moss_carpet = bid("moss_carpet")
    b.mossy_cobblestone = bid("mossy_cobblestone")
    b.mossy_stone_bricks = bid("mossy_stone_bricks")
    b.mud = bid("mud")
    b.mud_bricks = bid("mud_bricks")
    b.muddy_mangrove_roots = bid("muddy_mangrove_roots")
    b.mushroom_stem = bid("mushroom_stem")
    b.mycelium = bid("mycelium")
    b.nether_brick_fence = bid("nether_brick_fence")
    b.nether_brick_stairs = bid("nether_brick_stairs")
    b.nether_bricks = bid("nether_bricks")
    b.nether_gold_ore = bid("nether_gold_ore")
    b.nether_portal = bid("nether_portal")
    b.nether_quartz_ore = bid("nether_quartz_ore")
    b.nether_sprouts = bid("nether_sprouts")
    b.nether_wart = bid("nether_wart")
    b.nether_wart_block = bid("nether_wart_block")
    b.netherite_block = bid("netherite_block")
    b.netherrack = bid("netherrack")
    b.note_block = bid("note_block")
    b.oak_door = bid("oak_door")
    b.oak_fence = bid("oak_fence")
    b.oak_leaves = bid("oak_leaves")
    b.oak_log = bid("oak_log")
    b.oak_planks = bid("oak_planks")
    b.oak_sapling = bid("oak_sapling")
    b.oak_trapdoor = bid("oak_trapdoor")
    b.observer = bid("observer")
    b.obsidian = bid("obsidian")
    b.orange_terracotta = bid("orange_terracotta")
    b.orange_tulip = bid("orange_tulip")
    b.oxeye_daisy = bid("oxeye_daisy")
    b.packed_ice = bid("packed_ice")
    b.packed_mud = bid("packed_mud")
    b.peony = bid("peony")
    b.pink_tulip = bid("pink_tulip")
    b.piston = bid("piston")
    b.piston_head = bid("piston_head")
    b.pitcher_crop = bid("pitcher_crop")
    b.pitcher_plant = bid("pitcher_plant")
    b.podzol = bid("podzol")
    b.pointed_dripstone = bid("pointed_dripstone")
    b.polished_blackstone_bricks = bid("polished_blackstone_bricks")
    b.polished_blackstone_button = bid("polished_blackstone_button")
    b.polished_blackstone_pressure_plate = bid("polished_blackstone_pressure_plate")
    b.poppy = bid("poppy")
    b.potatoes = bid("potatoes")
    b.powder_snow = bid("powder_snow")
    b.powered_rail = bid("powered_rail")
    b.prismarine = bid("prismarine")
    b.prismarine_bricks = bid("prismarine_bricks")
    b.pumpkin = bid("pumpkin")
    b.pumpkin_stem = bid("pumpkin_stem")
    b.purple_stained_glass = bid("purple_stained_glass")
    b.purpur_block = bid("purpur_block")
    b.purpur_pillar = bid("purpur_pillar")
    b.purpur_slab = bid("purpur_slab")
    b.purpur_stairs = bid("purpur_stairs")
    b.rail = bid("rail")
    b.red_bed = bid("red_bed")
    b.red_carpet = bid("red_carpet")
    b.red_mushroom = bid("red_mushroom")
    b.red_mushroom_block = bid("red_mushroom_block")
    b.red_sand = bid("red_sand")
    b.red_sandstone = bid("red_sandstone")
    b.red_terracotta = bid("red_terracotta")
    b.red_tulip = bid("red_tulip")
    b.redstone_block = bid("redstone_block")
    b.redstone_lamp = bid("redstone_lamp")
    b.redstone_lamp_on = bid("redstone_lamp_on")
    b.redstone_ore = bid("redstone_ore")
    b.redstone_torch = bid("redstone_torch")
    b.redstone_torch_off = bid("redstone_torch_off")
    b.redstone_wire = bid("redstone_wire")
    b.reinforced_deepslate = bid("reinforced_deepslate")
    b.repeater = bid("repeater")
    b.repeater_on = bid("repeater_on")
    b.respawn_anchor = bid("respawn_anchor")
    b.rooted_dirt = bid("rooted_dirt")
    b.rose_bush = bid("rose_bush")
    b.sand = bid("sand")
    b.sandstone = bid("sandstone")
    b.sandstone_slab = bid("sandstone_slab")
    b.sandstone_stairs = bid("sandstone_stairs")
    b.sandstone_wall = bid("sandstone_wall")
    b.sculk = bid("sculk")
    b.sculk_catalyst = bid("sculk_catalyst")
    b.sculk_sensor = bid("sculk_sensor")
    b.sculk_shrieker = bid("sculk_shrieker")
    b.sculk_vein = bid("sculk_vein")
    b.sea_lantern = bid("sea_lantern")
    b.sea_pickle = bid("sea_pickle")
    b.short_grass = bid("short_grass")
    b.shroomlight = bid("shroomlight")
    b.shulker_box = bid("shulker_box")
    b.skeleton_skull = bid("skeleton_skull")
    b.slime_block = bid("slime_block")
    b.small_amethyst_bud = bid("small_amethyst_bud")
    b.small_dripleaf = bid("small_dripleaf")
    b.smithing_table = bid("smithing_table")
    b.smoker = bid("smoker")
    b.smoker_lit = bid("smoker_lit")
    b.smooth_basalt = bid("smooth_basalt")
    b.smooth_sandstone = bid("smooth_sandstone")
    b.sniffer_egg = bid("sniffer_egg")
    b.snow = bid("snow")
    b.snow_block = bid("snow_block")
    b.soul_campfire = bid("soul_campfire")
    b.soul_fire = bid("soul_fire")
    b.soul_lantern = bid("soul_lantern")
    b.soul_sand = bid("soul_sand")
    b.soul_soil = bid("soul_soil")
    b.spawner = bid("spawner")
    b.spore_blossom = bid("spore_blossom")
    b.spruce_leaves = bid("spruce_leaves")
    b.spruce_log = bid("spruce_log")
    b.spruce_planks = bid("spruce_planks")
    b.spruce_sapling = bid("spruce_sapling")
    b.sticky_piston = bid("sticky_piston")
    b.stone = bid("stone")
    b.stone_brick_slab = bid("stone_brick_slab")
    b.stone_brick_stairs = bid("stone_brick_stairs")
    b.stone_bricks = bid("stone_bricks")
    b.stone_button = bid("stone_button")
    b.stone_pressure_plate = bid("stone_pressure_plate")
    b.stonecutter = bid("stonecutter")
    b.sugar_cane = bid("sugar_cane")
    b.suspicious_gravel = bid("suspicious_gravel")
    b.suspicious_sand = bid("suspicious_sand")
    b.sweet_berry_bush = bid("sweet_berry_bush")
    b.tall_grass = bid("tall_grass")
    b.tall_seagrass = bid("tall_seagrass")
    b.target = bid("target")
    b.terracotta = bid("terracotta")
    b.tnt = bid("tnt")
    b.torch = bid("torch")
    b.torchflower = bid("torchflower")
    b.torchflower_crop = bid("torchflower_crop")
    b.trapped_chest = bid("trapped_chest")
    b.tripwire = bid("tripwire")
    b.tripwire_hook = bid("tripwire_hook")
    b.tuff = bid("tuff")
    b.turtle_egg = bid("turtle_egg")
    b.twisting_vines = bid("twisting_vines")
    b.vine = bid("vine")
    b.void_air = bid("void_air")
    b.warped_fungus = bid("warped_fungus")
    b.warped_nylium = bid("warped_nylium")
    b.warped_roots = bid("warped_roots")
    b.warped_stem = bid("warped_stem")
    b.warped_wart_block = bid("warped_wart_block")
    b.water = bid("water")
    b.weeping_vines = bid("weeping_vines")
    b.wet_sponge = bid("wet_sponge")
    b.wheat = bid("wheat")
    b.white_carpet = bid("white_carpet")
    b.white_terracotta = bid("white_terracotta")
    b.white_tulip = bid("white_tulip")
    b.white_wool = bid("white_wool")
    b.wither_skeleton_skull = bid("wither_skeleton_skull")
    b.yellow_terracotta = bid("yellow_terracotta")
    B = b
}
